name: Build API

on:
  workflow_call:
    inputs:
      build-needed:
        required: false
        type: boolean
        default: true
      upload-artifact:
        required: false
        type: boolean
        description: Upload the resulting artifact to make available for a deployment
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      if: inputs.build-needed
      uses: actions/checkout@v3

    - name: Get Lambda Runtime
      if: inputs.build-needed
      run: pip3 install cargo-lambda

    - name: Run tests
      if: inputs.build-needed
      working-directory: ./api
      run: cargo test --verbose

    - name: Build
      if: inputs.build-needed
      working-directory: ./api
      run: cargo lambda build --verbose --release --output-format zip
    
    - name: Upload artifact
      if: ${{ inputs.upload-artifact && inputs.build-needed }}
      uses: actions/upload-artifact@v2
      with:
        name: rust-api-artifact
        path: ./api/target/lambda/s3-sample/bootstrap.zip
