name: Build

on:
  pull_request:
    branches:
      - 'master'

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.api }}
    steps:
    - uses: actions/checkout@v3
    - name: Check sha
      run: git log
      shell: bash
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          api:
            - './api/**'

  build-api:
    runs-on: ubuntu-latest
    needs: paths-filter
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/build-api.yaml
        if: ${{ needs.paths-filter.outputs.output1 }}
        with:
          upload-artifact: false
