name: Deploy

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Lambda Runtime
      run: pip3 install cargo-lambda

    - name: Run tests
      working-directory: ./api
      run: cargo test --verbose

    - name: Build
      working-directory: ./api
      run: cargo lambda build --verbose --release --output-format zip
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rust-api-artifact
        path: ./api/target/lambda/s3-sample/bootstrap.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

    - name: Deploy Preliminary CloudFormation stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: rust-test-prelim-stack
        template: ./iac/agent-dependencies.yaml 
          # capabilities: CAPABILITIY_NAMED_IAM
        parameter-overrides: |
          ArtifactBucketPrefix=artifacts

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: rust-api-artifact
        path: ./target/bootstrap.zip

    - name: Upload artifact to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
          AWS_S3_BUCKET: artifacts.rust-test.thestillheron.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: 'target'

    - name: Deploy Resource CloudFormation stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: rust-test-resource-stack
        template: ./iac/resources.yaml 
        capabilities: CAPABILITIY_NAMED_IAM
        parameter-overrides: |
          ArtifactBucketPrefix=artifacts
          ZipPath=bootstrap.zip

