name: Deploy

on:
  push:
    branches: [ "master" ]
jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.api }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          api:
            - './api/**'

  build-api:
    needs: paths-filter
    uses: ./.github/workflows/build-api.yaml
    if: ${{ needs.paths-filter.outputs.output1 }}
    with:
      upload-artifact: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

    - name: Deploy Preliminary CloudFormation stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: rust-test-prelim-stack
        template: ./iac/agent-dependencies.yaml 
        no-fail-on-empty-changeset: "1"
          # capabilities: CAPABILITIY_NAMED_IAM
        parameter-overrides: |
          ArtifactBucketPrefix=artifacts

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: rust-api-artifact
        path: ./target

    - name: Upload artifact to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
          AWS_S3_BUCKET: artifacts.rust-test.thestillheron.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: 'target'

    - name: Deploy Resource CloudFormation stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: rust-test-resource-stack
        template: ./iac/resources.yaml 
        no-fail-on-empty-changeset: "1"
        capabilities: CAPABILITY_NAMED_IAM
        parameter-overrides: ArtifactBucketPrefix=artifacts,ZipPath=bootstrap.zip

