on:
  push:
    branches-ignore:
      - main
      - develop
  workflow_dispatch:
    inputs:
      branchName: 
        description: 'Branch name'
        required: true

jobs:
  showLog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.events.inputs.branchName || github.events.payload.ref }}
      - shell: bash
        name: Log branch name
        run: echo ${{ github.events.inputs.branchName }}
      - shell: bash
        name: Log sha
        run: git log

